#-----------------------------------------------------------------------------------------------------------------------
#   Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
#  and limitations under the License.
#-----------------------------------------------------------------------------------------------------------------------
neptuneUrl:
aws:
  region:
  iot:
    endpoint:

events:
  groups:
    topic: cdf/assetlibrary/events/groups/{objectId}/{event}
  devices:
    topic: cdf/assetlibrary/events/devices/{objectId}/{event}
  policies:
    topic: cdf/assetlibrary/events/policies/{objectId}/{event}
  groupTemplates:
    topic: cdf/assetlibrary/events/groupTemplates/{objectId}/{event}
  deviceTemplates:
    topic: cdf/assetlibrary/events/deviceTemplates/{objectId}/{event}
  profiles:
    topic: cdf/assetlibrary/events/profiles/{objectId}/{event}

defaults:
  devices:
    parent:
      relation: parent
      groupPath: /unprovisioned
    state: unprovisioned
  groups:
    validateAllowedParentPaths: false

cors:
  origin:
  exposedHeaders:

mode: full

cache:
  types:
    ttl: 30

supportedApiVersions:
  - json:
      - '1.0'
      - '2.0'

authorization:
  enabled: false

logging:
  level: debug

customDomain:
  basePath:
