#-----------------------------------------------------------------------------------------------------------------------
#   Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
#  and limitations under the License.
#-----------------------------------------------------------------------------------------------------------------------
aws:
  accountId: 
  region: 

  dynamodb:
    table:
      simulations: cdf-simulation
      state: cdf-simulation-device-state

  iot:
    host:
  s3:
    bucket:
    prefix: simulations/

  sns:
    topics:
      launch:

cdf:
  assetlibrary:
    apiFunctionName:
    mimetype: application/vnd.aws-cdf-v1.0+json

runners:
  # local working directory
  dataDir: /opt/apache-jmeter-5.4.2/bin/cdf
  # task memory (MiB) per task instance
  memory: 2048
  # task cpu (units) per task instance
  cpu: 1024
  # total no. of threads to manage per task instance
  threads: 20

templates:
  provisioning: packages/services/simulation-manager/src/templates/provisioning.task.properties
  simulation: packages/services/simulation-manager/src/templates/simulation.task.properties

cors:
  origin:

logging:
  level: debug
